# Generated by Django 4.2 on 2023-04-10 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exptTitle', models.CharField(max_length=50)),
                ('exptDesc', models.CharField(max_length=100)),
                ('exptDate', models.DateField()),
                ('numberOfSeats', models.IntegerField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBooked', models.DateField(auto_now_add=True)),
                ('exptStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('paid ', 'Paid ')], default='pending', max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.slot')),
            ],
        ),
    ]
