# Generated by Django 4.2 on 2023-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_order_exptstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='exptStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid ', 'Paid '), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
