# Generated by Django 4.2 on 2023-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_order_isbooked_alter_order_exptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateBooked',
            field=models.DateField(),
        ),
    ]
